import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { admin, getSetting, notify } from "./platform.server";
import type { PaymentSettings } from "./platform.server";

const checkoutSchema = z.object({
  items: z
    .array(z.object({ productId: z.string().uuid(), quantity: z.number().int().min(1).max(20) }))
    .min(1)
    .max(30),
  referralCode: z.string().trim().max(32).optional().nullable(),
  shippingName: z.string().trim().min(2).max(100),
  mobile: z
    .string()
    .trim()
    .regex(/^[0-9]{10}$/),
  address: z.string().trim().min(5).max(300),
  city: z.string().trim().min(2).max(80),
  state: z.string().trim().min(2).max(80),
  pincode: z
    .string()
    .trim()
    .regex(/^[0-9]{6}$/),
});

/**
 * Places an order. Prices, totals and referral attribution are resolved
 * server-side from the database — never trusted from the browser.
 * Commission is generated by the database engine when status becomes `paid`.
 */
export const placeOrder = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => checkoutSchema.parse(input))
  .handler(async ({ data, context }) => {
    const db = await admin();
    const ids = data.items.map((i) => i.productId);
    const { data: products } = await db
      .from("products")
      .select("id,name,price,sale_price,stock,status")
      .in("id", ids);
    if (!products || products.length === 0)
      return { ok: false as const, error: "Products are no longer available." };

    const lines = data.items.flatMap((item) => {
      const product = products.find((p) => p.id === item.productId);
      if (!product || product.status !== "active") return [];
      const unit = Number(product.sale_price ?? product.price);
      return [
        {
          product_id: product.id,
          product_name: product.name,
          unit_price: unit,
          quantity: item.quantity,
          line_total: Number((unit * item.quantity).toFixed(2)),
        },
      ];
    });
    if (lines.length === 0)
      return { ok: false as const, error: "None of the items in your cart are available." };

    const subtotal = Number(lines.reduce((s, l) => s + l.line_total, 0).toFixed(2));
    const shipping = subtotal >= 999 ? 0 : 59;
    const total = Number((subtotal + shipping).toFixed(2));

    // Referral attribution — self referral is never rewarded.
    let partnerId: string | null = null;
    let referralCode: string | null = null;
    if (data.referralCode) {
      const { data: partner } = await db
        .from("partners")
        .select("id,user_id,status")
        .eq("referral_code", data.referralCode.toUpperCase())
        .maybeSingle();
      if (partner && partner.status === "active" && partner.user_id !== context.userId) {
        partnerId = partner.id;
        referralCode = data.referralCode.toUpperCase();
      }
    }

    await db.from("profiles").upsert({
      id: context.userId,
      full_name: data.shippingName,
      mobile: data.mobile,
      address: data.address,
      city: data.city,
      state: data.state,
      pincode: data.pincode,
    });

    const { data: order, error } = await db
      .from("orders")
      .insert({
        customer_id: context.userId,
        referral_code: referralCode,
        partner_id: partnerId,
        subtotal,
        shipping,
        total,
        status: "payment_pending",
      })
      .select("*")
      .single();
    if (error || !order) return { ok: false as const, error: "Could not create your order." };

    await db.from("order_items").insert(lines.map((l) => ({ ...l, order_id: order.id })));
    return { ok: true as const, orderId: order.id, orderNumber: order.order_number, total };
  });

/** Confirms payment for an order; demo mode simulates a successful gateway. */
export const payForOrder = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => z.object({ orderId: z.string().uuid() }).parse(input))
  .handler(async ({ data, context }) => {
    const db = await admin();
    const { data: order } = await db
      .from("orders")
      .select("*")
      .eq("id", data.orderId)
      .eq("customer_id", context.userId)
      .maybeSingle();
    if (!order) return { ok: false as const, error: "Order not found." };
    if (order.status !== "payment_pending" && order.status !== "created")
      return { ok: false as const, error: "This order has already been paid." };

    const payment = await getSetting<PaymentSettings>("payment", {
      provider: "razorpay",
      demo_mode: false,
    });
    if (!payment.demo_mode) {
      return {
        ok: false as const,
        error:
          "Payment gateway is not configured yet. Please try again after payment setup is completed.",
      };
    }

    const paymentId = `pay_${crypto.randomUUID().replace(/-/g, "").slice(0, 18)}`;
    const { error: transactionError } = await db.from("transactions").insert({
      user_id: context.userId,
      partner_id: order.partner_id,
      amount: order.total,
      gateway: "demo",
      gateway_order_id: order.order_number,
      gateway_payment_id: paymentId,
      status: "success",
      payment_type: "product_order",
    });
    if (transactionError) {
      return { ok: false as const, error: "Could not record the payment transaction." };
    }

    // The database commission engine fires on this status change.
    const { data: updatedOrder, error: updateError } = await db
      .from("orders")
      .update({ status: "paid", payment_id: paymentId })
      .eq("id", order.id)
      .eq("customer_id", context.userId)
      .in("status", ["payment_pending", "created"])
      .select("id")
      .maybeSingle();
    if (updateError || !updatedOrder) {
      return { ok: false as const, error: "Payment could not be confirmed for this order." };
    }

    await notify(
      context.userId,
      "Order confirmed",
      `Your order ${order.order_number} has been placed successfully.`,
      "order",
    );
    return { ok: true as const, orderNumber: order.order_number, paymentId };
  });
